---
- name: Deploy app to web
  hosts: oldweb
  remote_user: "{{deploy_user}}"
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../.."
    ansistrano_deploy_to: "/apps/{{ project_name }}"
    ansistrano_keep_releases: 3

    ansistrano_deploy_via: git
    ansistrano_git_repo: git@github.com:2rba/ansistrano-rails.git
    ansistrano_git_branch: master
    ansistrano_shared_paths:
      - log
      - tmp
      - vendor
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/tasks/prepare.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/restart.yml"
  roles:
    - { role: ansistrano.deploy }
